### ISSUE TITLE
无法通过osmap.mapLoad读取已保存的文件

### ISSUE THREAD

**Issue by AotoriChiaki** [yutongwangBIT/VOOM#10]
在Examples/rgbd_tum_with_ellipse.cc中，在`osmap.mapSave(output_folder + "map_" + output_name);`之后加入一行`osmap.mapLoad(output_folder + "map_" + output_name + ".yaml", false, false, "rgbd");`

运行命令：./rgbd_tum_with_ellipse ../Vocabulary/ORBvoc.txt ../Cameras/TUM2.yaml ../Data/fr2_desk/rgbd_dataset_freiburg2_desk ../Data/fr2_desk/fr2_desk.txt ../Data/fr2_desk/detections_yolov8x_seg_tum_rgbd_fr2_desk_with_ellipse.json points+objects fr2_desk

运行结果如下：
C++ version: 201703

OA-SLAM Copyright (C) 2022 Matthieu Zins, Inria, LORIA, Université de Lorraine;
Based on ORB-SLAM2;
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions.

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Camera Parameters: 
- fx: 520.909
- fy: 521.007
- cx: 325.141
- cy: 249.702
- k1: 0.231222
- k2: -0.784899
- k3: 0.917205
- p1: -0.003257
- p2: -0.000105
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Depth Threshold (Close/Far Points): 3.07156
Start Local Mapping: 
-------
Start processing sequence ...
Images in the sequence: 2893

New map created with 786 points
count:9Map has 9 objects
Wait until all thread have effectively stopped
-------

median tracking time: 0.0285293
mean tracking time: 0.0289898

Saved keyframe trajectory to fr2_desk/keyframes_poses_fr2_desk_tum.txt
Saved keyframe trajectory to fr2_desk/keyframes_poses_fr2_desk.json
Save map points in fr2_desk/map_points_fr2_desk.obj
Save map objects in fr2_desk/map_objects_fr2_desk.objwith 45objects.
Save map objects in fr2_desk/map_objects_fr2_desk.txt

Saving map_fr2_desk.mappoints
Saving map_fr2_desk.Objects
Saving map_fr2_desk.keyframes
Saving map_fr2_desk.graphs
Saving map_fr2_desk.features
Mappoints loaded: 0
Objects loaded: 0
Keyframes loaded: 0
!!!! GRAPH SIZE !!!!0
Graphs loaded: 0
Loading features from  ...
Features loaded: 0
Rebuilding map:
./run_fr2_desk.sh: line 6:  4408 Segmentation fault      (core dumped) ./rgbd_tum_with_ellipse ../Vocabulary/ORBvoc.txt ../Cameras/TUM2.yaml ../Data/fr2_desk/rgbd_dataset_freiburg2_desk ../Data/fr2_desk/fr2_desk.txt ../Data/fr2_desk/detections_yolov8x_seg_tum_rgbd_fr2_desk_with_ellipse.json points+objects fr2_desk

**Comment by yutongwangBIT** [comment]
如果你想使用保存的地图，可以看看GORELOC，[loc_tum.cc](https://github.com/yutongwangBIT/GOReloc/blob/main/Examples/loc_tum.cc)
，这里面有用到osmap.mapload。两个库的osmap有修改过，看的时候可以注意一下

**Comment by AotoriChiaki** [comment]
感谢回复，请问GORELOC是同时包含了VOOM的建图功能并且支持重定位，所以直接使用GORELOC就可以了吗

**Comment by yutongwangBIT** [comment]
是的
