### ISSUE TITLE
后端优化模块代码？

### ISSUE THREAD

**Issue by YongshuaiZ** [yutongwangBIT/VOOM#12]
作者你好，很感谢你的工作，不过目前有一个问题，在你的工作中，基于 Object 的物体对位姿的优化只体现在数据关联层面吗？在 OptimizerObject.h 中的代码只是用来优化 椭圆物体的，而没有优化系统的位姿吗？因为在 Optimizer.cc 中并没有发现统一的优化代码。

**Comment by yutongwangBIT** [comment]
![Screenshot from 2024-11-14 09-27-46](https://github.com/user-attachments/assets/5fbe91c6-a943-4e0d-966c-35c9a7c13ca4)
![Screenshot from 2024-11-14 09-26-07](https://github.com/user-attachments/assets/989c704c-b836-4e3a-952b-0b15fa7287ea)
![Screenshot from 2024-11-14 09-24-55](https://github.com/user-attachments/assets/a7ef9b90-e117-493e-b857-c675b53b8b34)
