### ISSUE TITLE
Is folder existed?

### ISSUE THREAD

**Issue by luyihsien** [yutongwangBIT/VOOM#2]
from CmakeList.txt :116 

add_executable(rgbd_tum_with_ellipse
Examples/rgbd_tum_with_ellipse.cc)
target_link_libraries(rgbd_tum_with_ellipse ${PROJECT_NAME})

add_executable(rgbd_diamond_with_ellipse
Examples/rgbd_diamond_with_ellipse.cc)
target_link_libraries(rgbd_diamond_with_ellipse ${PROJECT_NAME})

but I found the folder is not there

**Comment by yutongwangBIT** [comment]
Hi,
 I just updated the repository and uploaded the example folder yesterday, you might check it now.

**Comment by luyihsien** [comment]
I saw the update, thank you very much.
May I ask if I can discuss a SLAM-related issue with you? I've noticed that your team are experts in SLAM, with many excellent conferences and research.

**Comment by yutongwangBIT** [comment]
> I saw the update, thank you very much. May I ask if I can discuss a SLAM-related issue with you? I've noticed that your team are experts in SLAM, with many excellent conferences and research.

Sure, it's our pleasure.

**Comment by luyihsien** [comment]
Thx a lot~.I want to implement some decentralized SLAM work but met some obstacles.May I ask your multi-orbslam3 project on Github ?
