### ISSUE TITLE
How to run on your own dataset

### ISSUE THREAD

**Issue by wf-hahaha** [yutongwangBIT/VOOM#3]
HI, The author provided scripts for generating detection boxes, but it seems that the supporting files are not complete, such as how to obtain diamond_dji.json. What is the complete process of creating it? THANKS！

**Comment by yutongwangBIT** [comment]
Hi, you can find it at https://github.com/yutongwangBIT/VOOM/blob/main/PythonScripts/find_diamond_corresponds.py

And thanks for reminding us, we will update the README later.

**Comment by wf-hahaha** [comment]
OK,Thank you very much for your prompt response.

**Comment by yutongwangBIT** [comment]
readme.md for preparing data is updated: https://github.com/yutongwangBIT/VOOM/blob/main/PythonScripts/ReadMe.md

not finished about ros data, to be continued.
