### ISSUE TITLE
Does this support stereo cameras?

### ISSUE THREAD

**Issue by deepConnectionism** [yutongwangBIT/VOOM#4]
Thanks to the author's excellent work, I have run through TUM's RGB-D dataset. I want to know if this can support stereo cameras? If so, what should be done?

Looking forward to your reply！

**Comment by yutongwangBIT** [comment]
Hi,

Thank you for your kind words and for running our work. 

Our development primarily focuses on RGB-D, but supporting stereo cameras is theoretically feasible. Here are some steps to adapt the system that I am suggesting:

1. Modify Tracking.cc: Add object-related code in Tracking::GrabImageStereo similar to what's present in Tracking::GrabImageRGBD. Notably, in the RGB-D setup, the current_depth_data_per_det_ stores rough depth information. For stereo cameras, the method to obtain this depth information might differ. 

2. Example Usage: Write a source file for using stereo cameras in the [example](https://github.com/yutongwangBIT/VOOM/tree/main/Examples) directory. You can refer to the original ORB-SLAM2 and the examples we provide as a starting point.

Please note that while these are the main steps, there might be conflicts or additional modifications required when implementing the code. Feel free to reach out with any further questions or issues you encounter.

Looking forward to your updates and questions!

**Comment by deepConnectionism** [comment]
Thanks for the reply

I wonder if there are two ways, one is to use algorithms such as SGBM to get a depth map of the left image, and then use the code you provide. The other is to modify the source code you are talking about.

Which do you think would be better?

**Comment by yutongwangBIT** [comment]
Hi,

I am not sure. The first method may allow you to test the algorithm more quickly, while the second offers a more elegant engineering solution and is better suited for long-term experimentation. From my experience, writing the stereo part of the code could take as little as half a day if done quickly, or up to two days if taking a more measured approach. Feel free to give it a try, and if you encounter any issues, post them here and I'll do my best to help you resolve them.

Best Regards，
