### ISSUE TITLE
使用其他数据集的检测结果，运行其他数据集？

### ISSUE THREAD

**Issue by Geralt-of-winterfall** [yutongwangBIT/VOOM#6]
你好。
在使用PythonScripts中的脚本得到其他数据集的检测结果后，在运行voom-tum时，出现如下情况，无法重构出3D物体，pangolin地图中出现大量黑线，如下图所示。检查了检测结果文件，有2d-bbox和ell的检测结果，请问这种情况可能是什么原因造成的？
![image](https://github.com/yutongwangBIT/VOOM/assets/146155193/11b98dd6-ea3e-4075-8bb6-a3a514a0a338)

**Comment by yutongwangBIT** [comment]
你好 ，方便问一下使用的是什么样的数据集吗

**Comment by Geralt-of-winterfall** [comment]
组织形式和TUM类似的一个RGB-D数据集。
[ustc数据集](https://rec.ustc.edu.cn/share/bd180320-bc6d-11eb-9675-6d646d5cf84a),密码:epya
使用PythonScripts中的TUM脚本：
find_tum_corresponds.py需要：rgb和depth路径，GroundTruth。
generate_rgbd_association.py需要：上一步生成的json文件
generate_detection_association.py需要：上一步生成的json文件和pt文件。

数据集里包含第一步需要的所有数据，能得到检测结果。
有待商榷的是这个数据集里的GroundTruth帧数远远少于RGB帧数

**Comment by Geralt-of-winterfall** [comment]
> 组织形式和TUM类似的一个RGB-D数据集。 [ustc数据集](https://rec.ustc.edu.cn/share/bd180320-bc6d-11eb-9675-6d646d5cf84a),密码:epya 使用PythonScripts中的TUM脚本： find_tum_corresponds.py需要：rgb和depth路径，GroundTruth。 generate_rgbd_association.py需要：上一步生成的json文件 generate_detection_association.py需要：上一步生成的json文件和pt文件。
> 
> 数据集里包含第一步需要的所有数据，能得到检测结果。 有待商榷的是这个数据集里的GroundTruth帧数远远少于RGB帧数

**Comment by Geralt-of-winterfall** [comment]
> 你好。 在使用PythonScripts中的脚本得到其他数据集的检测结果后，在运行voom-tum时，出现如下情况，无法重构出3D物体，pangolin地图中出现大量黑线，如下图所示。检查了检测结果文件，有2d-bbox和ell的检测结果，请问这种情况可能是什么原因造成的？ ![image](https://private-user-images.githubusercontent.com/146155193/346559882-11b98dd6-ea3e-4075-8bb6-a3a514a0a338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzQ1MTgsIm5iZiI6MTcyMDU3NDIxOCwicGF0aCI6Ii8xNDYxNTUxOTMvMzQ2NTU5ODgyLTExYjk4ZGQ2LWVhM2UtNDA3NS04YmI2LWEzYTUxNGEwYTMzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwMTE2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjNjMWY4ZmYxNjhmZjY5ZmUxZTk0YmFmYTBiZWU5ZGFmZTcyY2M2MWMzZDMzMjQyNmM2OTQwNzZjNWYzNjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oHjrvk1zuxpk-MeXMEEWp6vidXfbAl7gzvchKUQvwY0)

这个部分的黑线应该是来自Object-Graph。那应该是重建了3D Object，但地图上没有显示，终端上也是0 Object

**Comment by yutongwangBIT** [comment]
这个数据集的图片大小是640*480吗？然后有尝试看bounding box是否绘制在正确的地方吗？另外，以下代码的阈值可能会影响使用的检测结果的个数：
https://github.com/yutongwangBIT/VOOM/blob/c8a9b1bf7bf6f71530d103e63646452286dfcfb3/src/Tracking.cc#L254-L275

**Comment by Geralt-of-winterfall** [comment]
> 这个数据集的图片大小是640*480吗？然后有尝试看bounding box是否绘制在正确的地方吗？另外，以下代码的阈值可能会影响使用的检测结果的个数：
> 
> https://github.com/yutongwangBIT/VOOM/blob/c8a9b1bf7bf6f71530d103e63646452286dfcfb3/src/Tracking.cc#L254-L275

**Comment by Geralt-of-winterfall** [comment]
确实是图像尺寸的问题，输入图像尺寸为1280x720，检测结果应该是有问题的，感谢答复。

**Comment by rich2300** [comment]
您好，换了数据集之后，运行卡在第一帧，没有继续往下运行，请问怎么解决呢？

**Comment by yutongwangBIT** [comment]
> 您好，换了数据集之后，运行卡在第一帧，没有继续往下运行，请问怎么解决呢？

可以检查一下读取的object个数？
