### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by allenthreee** [yutongwangBIT/VOOM#7]
If there are any plans to provide Docker support for VOOM. Dockerizing the project would greatly simplify the setup process and ensure a consistent environment across different systems, which would be beneficial for many users.

If Docker support is not currently planned, could you provide some guidance or a starting point for creating a Dockerfile for VOOM?

Thank you for your time and assistance.

**Comment by allenthreee** [comment]
I have made a docker image:


1. pull the docker image:
`docker pull allenthreee/voom_base_melodic:25th-July-1st_build`

2. run the image by the follow command (in a docker_run.sh)

```
#!/bin/bash
# build container

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

sudo docker run \
  -it \
  --network host \
  --privileged \
  --volume=$XSOCK:$XSOCK:rw \
  --volume=$XAUTH:$XAUTH:rw \
  --env="XAUTHORITY=${XAUTH}" \
  --env DISPLAY=$DISPLAY \
  --env TERM=xterm-256color \
  -v /dev:/dev \
  --name "voom_base" \
  allenthreee/voom_base_melodic:25th-July-1st_build \
  /bin/bash
```
 

3. inside the docker container:
`cd /root/VOOM-main/bin`
`./run_fr2_desk.sh`

**Comment by mirpouya** [comment]
> I have made a docker image:
> 
> 1. pull the docker image:
>    `docker pull allenthreee/voom_base_melodic:25th-July-1st_build`
> 2. run the image by the follow command (in a docker_run.sh)
> 
> ```
> #!/bin/bash
> # build container
> 
> XSOCK=/tmp/.X11-unix
> XAUTH=/tmp/.docker.xauth
> touch $XAUTH
> xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
> 
> sudo docker run \
>   -it \
>   --network host \
>   --privileged \
>   --volume=$XSOCK:$XSOCK:rw \
>   --volume=$XAUTH:$XAUTH:rw \
>   --env="XAUTHORITY=${XAUTH}" \
>   --env DISPLAY=$DISPLAY \
>   --env TERM=xterm-256color \
>   -v /dev:/dev \
>   --name "voom_base" \
>   allenthreee/voom_base_melodic:25th-July-1st_build \
>   /bin/bash
> ```
> 
> 3. inside the docker container:
>    `cd /root/VOOM-main/bin`
>    `./run_fr2_desk.sh`

The structure of this docker is very good and interesting, can I have the code to make this image? I am in the process of learning docker, and if you kindly let me see the image it is very apprecieated!

This is my emai: smirmoh2@uwo.ca

**Comment by allenthreee** [comment]
> > I have made a docker image:
> > 
> > 1. pull the docker image:
> >    `docker pull allenthreee/voom_base_melodic:25th-July-1st_build`
> > 2. run the image by the follow command (in a docker_run.sh)
> > 
> > ```
> > #!/bin/bash
> > # build container
> > 
> > XSOCK=/tmp/.X11-unix
> > XAUTH=/tmp/.docker.xauth
> > touch $XAUTH
> > xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
> > 
> > sudo docker run \
> >   -it \
> >   --network host \
> >   --privileged \
> >   --volume=$XSOCK:$XSOCK:rw \
> >   --volume=$XAUTH:$XAUTH:rw \
> >   --env="XAUTHORITY=${XAUTH}" \
> >   --env DISPLAY=$DISPLAY \
> >   --env TERM=xterm-256color \
> >   -v /dev:/dev \
> >   --name "voom_base" \
> >   allenthreee/voom_base_melodic:25th-July-1st_build \
> >   /bin/bash
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. inside the docker container:
> >    `cd /root/VOOM-main/bin`
> >    `./run_fr2_desk.sh`
> 
> The structure of this docker is very good and interesting, can I have the code to make this image? I am in the process of learning docker, and if you kindly let me see the image it is very apprecieated!
> 
> This is my emai: [smirmoh2@uwo.ca](mailto:smirmoh2@uwo.ca)

Hi, Pouya
Sorry for the late reply, have you figure out how the docker image work?
I simple build this project in a clean OSRF/ROS docker image.

Feel free to drop me an e-mail at wenyu.yang@connect.polyu.hk if you have any further questions:)
