### ISSUE TITLE
关于段错误 (核心已转储)的问题

### ISSUE THREAD

**Issue by sumin12345678** [yutongwangBIT/VOOM#9]
C++ version: 201703

OA-SLAM Copyright (C) 2022 Matthieu Zins, Inria, LORIA, Université de Lorraine;
Based on ORB-SLAM2;
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions.

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Camera Parameters: 
- fx: 520.909
- fy: 521.007
- cx: 325.141
- cy: 249.702
- k1: 0.231222
- k2: -0.784899
- k3: 0.917205
- p1: -0.003257
- p2: -0.000105
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Depth Threshold (Close/Far Points): 3.07156
Start Local Mapping: 
-------
Start processing sequence ...
Images in the sequence: 2893

New map created with 784 points
count:9Map has 9 objects
段错误 (核心已转储)

您帮我看一下
运行时碰到 段错误 (核心已转储)的问题,重新编译也没能解决

**Comment by sumin12345678** [comment]
原来是eigen库的原因，已经解决了，谢谢您，很棒的工作

**Comment by HaochenFeng0101** [comment]
> 原来是eigen库的原因，已经解决了，谢谢您，很棒的工作

Hi, how you solved the issue, i still got the error :

Eigen::internal::enable_if<(Eigen::internal::traits<OtherDerived>::Alignment > 0), void*>::type) const [with T = Eigen::Map<Eigen::Matrix<double, 3, 6, 0, 3, 6>, 64, Eigen::Stride<0, 0> >; Derived = Eigen::Map<Eigen::Matrix<double, 3, 6, 0, 3, 6>, 64, Eigen::Stride<0, 0> >; typename Eigen::internal::enable_if<(Eigen::internal::traits<OtherDerived>::Alignment > 0), void*>::type = void*]: Assertion `( ((internal::UIntPtr(m_data) % internal::traits<Derived>::Alignment) == 0) || (cols() * rows() * minInnerStride * sizeof(Scalar)) < internal::traits<Derived>::Alignment ) && "data is not aligned"' failed.
